--all                 Find all Markdown files for non-hidden folders  --auto                Ignore ts/te tags, Automatically at the end/head of the file  --head                The TOC is generated in the header of the file, requires --auto

diff --git a/gh-md-toc b/gh-md-toc
--- a/gh-md-toc
+++ b/gh-md-toc
@@ -23,7 +23,7 @@
 #       substr($0, match($0, "href=\"[^\"]+?\" ")+6, RLENGTH-8)
 #
 
-gh_toc_version="0.7.0"
+gh_toc_version="0.8.0"
 
 gh_user_agent="gh-md-toc v$gh_toc_version"
 
@@ -83,35 +83,37 @@ gh_toc_md2html() {
     fi
 }
 
-
 #
 # Is passed string url
 #
 gh_is_url() {
     case $1 in
-        https* | http*)
-            echo "yes";;
-        *)
-            echo "no";;
+    https* | http*)
+        echo "yes"
+        ;;
+    *)
+        echo "no"
+        ;;
     esac
 }
 
 #
 # TOC generator
 #
-gh_toc(){
+gh_toc() {
     local gh_src=$1
     local gh_src_copy=$1
     local gh_ttl_docs=$2
     local need_replace=$3
     local no_backup=$4
     local no_footer=$5
+    local auto=$6
+    local head=$7
 
     if [ "$gh_src" = "" ]; then
         echo "Please, enter URL or local path for a README.md"
         exit 1
     fi
-
 
     # Show "TOC" string only if working with one document
     if [ "$gh_ttl_docs" = "1" ]; then
@@ -139,43 +141,67 @@ gh_toc(){
     else
         local rawhtml=$(gh_toc_md2html "$gh_src")
         if [ "$rawhtml" == "XXNetworkErrorXX" ]; then
-             echo "Parsing local markdown file requires access to github API"
-             echo "Please make sure curl is installed and check your network connectivity"
-             exit 1
+            echo "Parsing local markdown file requires access to github API"
+            echo "Please make sure curl is installed and check your network connectivity"
+            exit 1
         fi
         if [ "$rawhtml" == "XXRateLimitXX" ]; then
-             echo "Parsing local markdown file requires access to github API"
-             echo "Error: You exceeded the hourly limit. See: https://developer.github.com/v3/#rate-limiting"
-             TOKEN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/token.txt"
-             echo "or place GitHub auth token here: ${TOKEN_FILE}"
-             exit 1
+            echo "Parsing local markdown file requires access to github API"
+            echo "Error: You exceeded the hourly limit. See: https://developer.github.com/v3/#rate-limiting"
+            TOKEN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/token.txt"
+            echo "or place GitHub auth token here: ${TOKEN_FILE}"
+            exit 1
         fi
-        local toc=`echo "$rawhtml" | gh_toc_grab "$gh_src_copy"`
+        local toc=$(echo "$rawhtml" | gh_toc_grab "$gh_src_copy")
         echo "$toc"
         if [ "$need_replace" = "yes" ]; then
+            local ts="<\!--ts-->"
+            local te="<\!--te-->"
             if grep -Fxq "<!--ts-->" $gh_src && grep -Fxq "<!--te-->" $gh_src; then
                 echo "Found markers"
             else
-                echo "You don't have <!--ts--> or <!--te--> in your file...exiting"
-                exit 1
+                if [ "$auto" = "yes" ]; then
+                    echo ""
+                    if [ "$head" = "yes" ]; then
+                        echo "!!! TOC will be automatically generated at the $gh_src head."
+                        # insert toc file
+                        if [[ "$(uname)" == "Darwin" ]]; then
+                            sed -i "" "1i\\
+${te}
+              " "$gh_src"
+                            sed -i "" "1i\\
+${ts}
+              " "$gh_src"
+                        else
+                            sed -i "1i\\${te}" "$gh_src"
+                            sed -i "1i\\${ts}" "$gh_src"
+                        fi
+                    else
+                        echo "!!! TOC will be automatically generated at the $gh_src end."
+                        echo "<!--ts-->" >>$gh_src
+                        echo "<!--te-->" >>$gh_src
+                    fi
+
+                else
+                    echo "You don't have <!--ts--> or <!--te--> in your file...exiting"
+                    exit 1
+                fi
             fi
-            local ts="<\!--ts-->"
-            local te="<\!--te-->"
-            local dt=`date +'%F_%H%M%S'`
+            local dt=$(date +'%F_%H%M%S')
             local ext=".orig.${dt}"
             local toc_path="${gh_src}.toc.${dt}"
-            local toc_footer="<!-- Added by: `whoami`, at: `date` -->"
+            local toc_footer="<!-- Added by: $(whoami), at: $(date) -->"
             # http://fahdshariff.blogspot.ru/2012/12/sed-mutli-line-replacement-between-two.html
             # clear old TOC
             sed -i${ext} "/${ts}/,/${te}/{//!d;}" "$gh_src"
             # create toc file
-            echo "${toc}" > "${toc_path}"
+            echo "${toc}" >"${toc_path}"
             if [ "${no_footer}" != "yes" ]; then
-                echo -e "\n${toc_footer}\n" >> "$toc_path"
+                echo -e "\n${toc_footer}\n" >>"$toc_path"
             fi
 
             # insert toc file
-            if [[ "`uname`" == "Darwin" ]]; then
+            if [[ "$(uname)" == "Darwin" ]]; then
                 sed -i "" "/${ts}/r ${toc_path}" "$gh_src"
             else
                 sed -i "/${ts}/r ${toc_path}" "$gh_src"
@@ -188,7 +214,7 @@ gh_toc(){
             if [ -z "${no_backup}" ]; then
                 echo "!! Origin version of the file: '${gh_src}${ext}'"
                 echo "!! TOC added into a separate file: '${toc_path}'"
-        fi
+            fi
             echo
         fi
     fi
@@ -220,7 +246,7 @@ gh_toc_grab() {
                     }
                     print sprintf("%*s", level*3, " ") "* [" text "](" gh_url  modified_href ")"
                     '
-    if [ `uname -s` == "OS/390" ]; then
+    if [ $(uname -s) == "OS/390" ]; then
         grepcmd="pcregrep -o"
         echoargs=""
         awkscript='{
@@ -247,25 +273,25 @@ gh_toc_grab() {
     #        </h1>
     #   became: The command <code>foo1</code></h1>
     sed -e ':a' -e 'N' -e '$!ba' -e 's/\n<\/h/<\/h/g' |
-    
-    # find strings that corresponds to template
-    $grepcmd '<a.*id="user-content-[^"]*".*</h[1-6]' |
-    
-    # remove code tags
-    sed 's/<code>//g' | sed 's/<\/code>//g' |
 
-    # remove g-emoji
-    sed 's/<g-emoji[^>]*[^<]*<\/g-emoji> //g' |
-    
-    # now all rows are like:
-    #   <a id="user-content-..." href="..."><span ...></span></a> ... </h1
-    # format result line
-    #   * $0 - whole string
-    #   * last element of each row: "</hN" where N in (1,2,3,...)
-    echo $echoargs "$(awk -v "gh_url=$1" "$awkscript")"
+        # find strings that corresponds to template
+        $grepcmd '<a.*id="user-content-[^"]*".*</h[1-6]' |
+
+        # remove code tags
+        sed 's/<code>//g' | sed 's/<\/code>//g' |
+
+        # remove g-emoji
+        sed 's/<g-emoji[^>]*[^<]*<\/g-emoji> //g' |
+
+        # now all rows are like:
+        #   <a id="user-content-..." href="..."><span ...></span></a> ... </h1
+        # format result line
+        #   * $0 - whole string
+        #   * last element of each row: "</hN" where N in (1,2,3,...)
+        echo $echoargs "$(awk -v "gh_url=$1" "$awkscript")"
 }
 
-        # perl -lpE 's/(\[[^\]]*\]\()(.*?)(\))/my ($pre, $in, $post)=($1, $2, $3) ; $in =~ s{\+}{ }g; $in =~ s{%}{\\x}g; $pre.$in.$post/ems')"
+# perl -lpE 's/(\[[^\]]*\]\()(.*?)(\))/my ($pre, $in, $post)=($1, $2, $3) ; $in =~ s{\+}{ }g; $in =~ s{%}{\\x}g; $pre.$in.$post/ems')"
 
 #
 # Returns filename only from full path or url
@@ -275,18 +301,29 @@ gh_toc_get_filename() {
 }
 
 #
+# Find all Markdown files for non-hidden folders
+#
+all_md_filename=""
+gh_all_md_filename() {
+    while IFS= read -r -d $'\0'; do
+        all_md_filename=" $all_md_filename $REPLY"
+    done < <(find . -path "*\/\.*" -prune -o -type f -name "*.md" -print0)
+}
+
+#
 # Options handlers
 #
 gh_toc_app() {
-    local need_replace="no"
-
-    if [ "$1" = '--help' ] || [ $# -eq 0 ] ; then
+    if [ "$1" = '--help' ] || [ $# -eq 0 ]; then
         local app_name=$(basename "$0")
         echo "GitHub TOC generator ($app_name): $gh_toc_version"
         echo ""
         echo "Usage:"
         echo "  $app_name [--insert] [--hide-footer] src [src]  Create TOC for a README file (url or local path)"
         echo "  $app_name [--no-backup] [--hide-footer] src [src]  Create TOC without backup, requires <!--ts--> / <!--te--> placeholders"
+        echo "  $app_name --all                 Find all Markdown files for non-hidden folders"
+        echo "  $app_name --auto                Ignore ts/te tags, Automatically at the end/head of the file"
+        echo "  $app_name --head                The TOC is generated in the header of the file, requires --auto"
         echo "  $app_name -                     Create TOC for markdown from STDIN"
         echo "  $app_name --help                Show help"
         echo "  $app_name --version             Show version"
@@ -296,13 +333,13 @@ gh_toc_app() {
     if [ "$1" = '--version' ]; then
         echo "$gh_toc_version"
         echo
-        echo "os:     `lsb_release -d | cut -f 2`"
-        echo "kernel: `cat /proc/version`"
-        echo "shell:  `$SHELL --version`"
+        echo "os:     $(lsb_release -d | cut -f 2)"
+        echo "kernel: $(cat /proc/version)"
+        echo "shell:  $($SHELL --version)"
         echo
         for tool in curl wget grep awk sed; do
             printf "%-5s: " $tool
-            echo `$tool --version | head -n 1`
+            echo $($tool --version | head -n 1)
         done
         return
     fi
@@ -314,14 +351,14 @@ gh_toc_app() {
             mkdir -p "$TMPDIR"
         fi
         local gh_tmp_md
-        if [ `uname -s` == "OS/390" ]; then
+        if [ $(uname -s) == "OS/390" ]; then
             local timestamp=$(date +%m%d%Y%H%M%S)
             gh_tmp_md="$TMPDIR/tmp.$timestamp"
         else
             gh_tmp_md=$(mktemp $TMPDIR/tmp.XXXXXX)
         fi
         while read input; do
-            echo "$input" >> "$gh_tmp_md"
+            echo "$input" >>"$gh_tmp_md"
         done
         gh_toc_md2html "$gh_tmp_md" | gh_toc_grab ""
         return
@@ -338,16 +375,35 @@ gh_toc_app() {
         shift
     fi
 
+    if [ "$1" = '--auto' ]; then
+        auto="yes"
+        shift
+    fi
+
+    if [ "$1" = '--head' ]; then
+        head="yes"
+        shift
+    fi
+
     if [ "$1" = '--hide-footer' ]; then
         need_replace="yes"
         no_footer="yes"
         shift
     fi
 
-    for md in "$@"
-    do
+    if [ "$1" = '--all' ]; then
+        gh_all_md_filename
+        gh_toc_app $all_md_filename
+        return
+    fi
+
+    if [ "$need_replace" != "yes" ]; then
+        need_replace="no"
+    fi
+
+    for md in "$@"; do
         echo ""
-        gh_toc "$md" "$#" "$need_replace" "$no_backup" "$no_footer"
+        gh_toc "$md" "$#" "$need_replace" "$no_backup" "$no_footer" "$auto" "$head"
     done
 
     echo ""
@@ -358,4 +414,3 @@ gh_toc_app() {
 # Entry point
 #
 gh_toc_app "$@"
-
